---
# Playbook to undeploy Ghost and its component

- name: Deploy ghost
  hosts: localhost
  gather_facts: false
  roles:
      - undeploy_ghost
      - role: undeploy_mysql
        when: delete_data is defined and delete_data == "true"
      - role: delete_namespace
        when: delete_data is defined and delete_data == "true"
