- name: Deploy Ghost
  kubernetes.core.k8s:
    state: present
    namespace: "{{ ghost_namespace }}"
    kind: Deployment
    wait: true
    definition:
      apiVersion: apps/v1
      metadata:
        name: ghost-deployment
        labels:
          app: ghost
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: ghost
        template:
          metadata:
            labels:
              app: ghost
          spec:
            containers:
            - name: ghost
              image: ghost:5.14.1
              env:
              - name: database__client
                value: mysql
              - name: database__connection__host
                value: "{{ ghost_db_host }}"
              - name: database__connection__user
                value: "{{ ghost_db_user }}"
              - name: database__connection_port
                value: "3306"
              - name: database__connection__database
                value: "{{ ghost_db_name }}"
              - name: database__connection__password
                value: "{{ ghost_db_pw }}"
              - name: url
                value: http://{{ ghost_ip }}:{{ ghost_port }}

              ports:
              - containerPort: 2368


# Service for exposing Ghost
- name: Expose Ghost
  kubernetes.core.k8s:
    state: present
    namespace: "{{ ghost_namespace }}"
    kind: Service
    wait: true
    definition:
      apiVersion: v1
      metadata:
        name: ghost-service 
        labels:
          app: ghost
      spec:
        type: LoadBalancer
        selector:
          app: ghost
        ports:
          - name: http
            targetPort: 2368 # port that containers are listening on
            port: "{{ ghost_port }}" # port number exposed internally in the cluster


- name: Hash password
  shell:
    cmd: python3 scripts/digest.py "{{ blog_admin_pw }}"
  register: hashed_pw

- name: Get mysql pod name
  shell:
    cmd: kubectl get pod -n "{{ ghost_namespace }}" | perl -e 'while(<STDIN>){ if(m/mysql/){ print((split " ")[0]); last; }}'
  register: mysql_pod

- name: Add Blog user to the DB
  kubernetes.core.k8s_exec:
    namespace: "{{ ghost_namespace }}"
    pod: "{{ mysql_pod.stdout }}"
    command: mysql -h "{{ ghost_db_host }}" -u "{{ ghost_db_user }}" -p"{{ ghost_db_pw }}" -D "{{ ghost_db_name }}" -e 'UPDATE users set name="{{ blog_admin_name }}", password="{{hashed_pw.stdout}}", email="{{ blog_admin_email }}", status="active" WHERE id=1;'
