
- name: Set up Ghost user, give it super user perms and login as said user
  become: true
  shell:
    cmd: adduser "{{ ghost_user }}" && usermod -aG sudo "{{ ghost_user }}" && su - "{{ ghost_user }}" 

- name: Install nginx
  become: true
  apt:
    name: nginx

- name: Download NodeJS 16 setup script
  shell:
    cmd: curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -

- name: Install NodeJS 16
  become: true
  apt:
    name: nodejs

- name: Install MySQL Server
  become: true
  apt:
    name: mysql-server

- name: Install Ghost-CLI
  become: true
  shell:
    cmd: npm install ghost-cli@1.23.0 -g

- name: Create directory, and set the owner and permissions
  become: true
  shell:
    cmd: mkdir -p "{{ ghost_dir }}" && chown "{{ ghost_user }}":"{{ ghost_user }}" "{{ ghost_dir }}" && chmod 775 "{{ ghost_dir }}"

- name: Install Ghost
  shell:
    chdir: "{{ ghost_dir }}" 
    cmd: ghost install --url "{{ ghost_url }}" --port "{{ ghost_port }}" --ip "{{ ghost_ip }}" --dbhost "{{ ghost_db_host }}" --dbuser "{{ ghost_db_user }}" --dbpass "{{ ghost_db_pw }}" --dbname "{ ghost_db_name }}" --no-stetup-nginx --no-stetup-ssl --no-stetup-systemd --no-prompt


- name: Start Ghost
  shell:
    chdir: "{{ ghost_dir }}"
    cmd: ghost start --dir .

