- name: Deploy Ghost
  kubernetes.core.k8s:
    state: present
    namespace: "{{ ghost_namespace }}"
    kind: Deployment
    definition:
      apiVersion: apps/v1
      metadata:
        name: ghost-deployment
        labels:
          app: ghost
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: ghost
        template:
          metadata:
            labels:
              app: ghost
          spec:
            containers:
            - name: ghost
              image: ghost:5.14.1
              env:
              - name: database__client
                value: mysql
              - name: database__connection__host
                value: "{{ ghost_db_host }}"
              - name: database__connection__user
                value: "{{ ghost_db_user }}"
              - name: database__connection_port
                value: "3306"
              - name: database__connection__database
                value: "{{ ghost_db_name }}"
              - name: database__connection__password
                value: my_epic_password
                #value: \$2b\$10\$IT1m1RdpubBI/umopBHHguN.DSaA0pMYGxNDVfyw/NGf/9YuF6vw2
              - name: url
                value: http://{{ ghost_ip ~ ':' ~ ghost_port }}
                #- name: server__host
                #  value: "{{ ghost_ip }}"
                #- name: server__port
                #  value: "{{ '' ~ ghost_port }}"
              ports:
              - containerPort: "{{ ghost_port }}"


# Service for exposing Ghost
- name: Expose Ghost
  kubernetes.core.k8s:
    state: present
    namespace: "{{ ghost_namespace }}"
    kind: Service
    definition:
      apiVersion: v1
      metadata:
        name: ghost-service 
        labels:
          app: ghost
      spec:
        type: LoadBalancer
        selector:
          app: ghost
        ports:
          - name: http
            targetPort: "{{ ghost_port }}" # port that containers are listening on
            port: 2368 # port number exposed internally in the cluster
              #externalIps:
              #  - "{{ ghost_ip }}"
