- name: Delete k8s namespace
  kubernetes.core.k8s:
    name: "{{ ghost_namespace }}"
    state: absent
    api_version: v1
    kind: Namespace

- name: Wait for every resource to be deleted
  shell:
    cmd: perl scripts/wait_resource_deletion.pl "{{ ghost_namespace }}"
