- name: Delete MySQL service
  kubernetes.core.k8s:
    state: absent
    namespace: "{{ ghost_namespace }}"
    kind: Service
    definition:
      apiVersion: v1
      metadata:
        name: "{{ ghost_db_host }}" # logical name of the service, which will also become the DNS name of the service when it is created.
        labels:
          app: mysql
          tier: database


- name: Undeploy MySQL
  kubernetes.core.k8s:
    state: absent
    namespace: "{{ ghost_namespace }}"
    kind: Deployment
    definition:
      apiVersion: apps/v1
      metadata:
        name: mysql-deployment
        labels:
          app: mysql
          tier: database
